import mods.thermalexpansion.Compactor;


var materials = [
  'Mithril', 
  'Aluminium', 
  'Silver', 
  'Gold', 
  'Copper', 
  'Nickel', 
  'Magnesium', 
  'RedSteel', 
  'Steel', 
  'BlackSteel', 
  'BlackBronze',
  'SterlingSilver',
  'Bismuth',
  'Tin',
  'Boron',
  'Cobalt',
  'Ardite',
  'NickelSilver',
  'Antimony',
  'Osmium',
  'VibrantAlloy',
  'RedAlloy',
  'RedstoneAlloy',
  'PulsatingIron',
  'Manyullyn',
  'Invar',
  'EndSteel',
  'DarkSteel',
  'BlueSteel',
  'CrudeSteel',
  'ConductiveIron',
  'Bronze',
  'BismuthBronze',
  'Uranium',
  'Thorium',
  'Platinum',
  'Extreme',
  'HardCarbon',
  'Tough',
  'Lumium',
  'Signalum',
  'Brass',
  'RefinedObsidian',
  'RefinedGlowstone',
  'LeadPlatinum',
  'Zinc',
  'WroughtIron',
  'Tungsten',
  'TungstenSteel',
  'Titanium'
  ] as string[];

for mat in materials {
  Compactor.addPressRecipe(oreDict['plateDense'+mat].firstItem, oreDict['plate'+mat].firstItem*9, 4000);
}